### ISSUE TITLE
[BUG]: Unable to set cracker error action

### ISSUE THREAD

**Issue by Allesanddro** [s3inlc/hashtopussy#1023]
### Version Information

0.14.0 4c9b308

### Description

![image](https://github.com/hashtopolis/server/assets/23656101/0017d475-7256-489a-9d44-21607015c0fc) [all ips shown are NAT ips]
setting error action on cracker results in this 

fresh install guided by the wiki 
Hostsystem: Distributor ID: Ubuntu
Description:    Ubuntu 23.04
Release:        23.04
Codename:       lunar

Docker: Client: Docker Engine - Community
 Version:           24.0.7
 API version:       1.43
 Go version:        go1.20.10
 Git commit:        afdd53b
 Built:             Thu Oct 26 09:07:51 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          24.0.7
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.10
  Git commit:       311b9ff
  Built:            Thu Oct 26 09:07:51 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.24
  GitCommit:        61f9fd88f79f081d64d6fa3bb1a0dc71ec870523
 runc:
  Version:          1.1.9
  GitCommit:        v1.1.9-0-gccaecfc
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

`hashtopolis-backend   | [Mon Nov 06 19:37:06.786755 2023] [php:error] [pid 34] [client 100.125.164.111:61122] PHP Fatal error:  Uncaught Slim\\Exception\\HttpNotFoundException: Not found. in /var/www/html/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php:76\nStack trace:\n#0 /var/www/html/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php(44): Slim\\Middleware\\RoutingMiddleware->performRouting()\n#1 /var/www/html/vendor/slim/slim/Slim/MiddlewareDispatcher.php(121): Slim\\Middleware\\RoutingMiddleware->process()\n#2 /var/www/html/vendor/slim/slim/Slim/MiddlewareDispatcher.php(65): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()\n#3 /var/www/html/vendor/slim/slim/Slim/App.php(199): Slim\\MiddlewareDispatcher->handle()\n#4 /var/www/html/vendor/slim/slim/Slim/App.php(183): Slim\\App->handle()\n#5 /var/www/html/src/api/v2/index.php(277): Slim\\App->run()\n#6 {main}\n  thrown in /var/www/html/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php on line 76, referer: http://bbw-server:4200/`

**Comment by xbenyx** [comment]
Hi Allesanddro,

Thank you for taking the time to report this issue. We appreciate your diligence in helping us improve our project. 

I was able to replicate the issue. We will keep you updated on our progress and let you know as soon as we have a resolution.

**Comment by ObsidianOracle** [comment]
Can you please test in the new ui? If the error doesnt occur anymore, we keep the ticket closed.
