### ISSUE TITLE
[BUG]: Int too small for AgentStatsId

### ISSUE THREAD

**Issue by zyronix** [s3inlc/hashtopussy#1047]
### Version Information

0.14.1

### Description

In case of a long running hashtopolis environment, you can run into the int being too small for storing ids of some of the stats or logging entries.

As an example, this will result in something like this, an agent trying to submit progress:

```
[php:error] [pid 31340] PHP Fatal error:  Uncaught PDOException: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '2147483647' for key 'AgentStat.PRIMARY' inAbstractModelFactory.class.php:115

Stack trace:
#0 hashtopolis/dba/AbstractModelFactory.class.php(115): PDOStatement->execute()
#1 hashtopolis/dba/models/AgentStatFactory.class.php(80): DBA\\AbstractModelFactory->save()
#2 hashtopolis/inc/api/APISendProgress.class.php(99): DBA\\AgentStatFactory->save()
#3 hashtopolis/api/server.php(141): APISendProgress->execute()
#4 {main}
thrown in hashtopolis/dba/AbstractModelFactory.class.php on line 115
```

This is because the key is created as a int(11). Simple fix for this is:

```
ALTER TABLE AgentStat MODIFY agentStatId BIGINT AUTO_INCREMENT;
```

@s3inlc there are multiple solutions
1. we could increase the INT to BIGINT for just AgentStat
2. we could increase them for all stat/log tables (Speed, AgentStat, Log, maybe others?)
3. we could increase all ints to 64 int by default

Any preference?

**Comment by s3inlc** [comment]
Implement the proposals in 1. and 2.
