### ISSUE TITLE
mask-attack

### ISSUE THREAD

**Issue by master12210** [s3inlc/hashtopussy#136]
-a 3 -1 ?l?d ?1?1?1?1?1 attacks dont work for me setting up with:
Something went wrong with keyspace measuring
You need to specify a mask if you specify a custom-charset

Unhandled Exception: System.FormatException: Input string was not in a correct format.
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt64(String value, NumberStyles options, NumberFormatInfo numfmt)
   at System.Convert.ToInt64(String value)
   at hashtopussy.hashcatClass.parseKeyspace(String line, Int64& keySpace)
   at hashtopussy.hashcatClass.runKeyspace(Int64& keySpace)
   at hashtopussy.taskClass.getChunk(Int32 inTask)
   at hashtopussy.taskClass.getTask()
   at hashtopussy.Program.Main(String[] args)

**Comment by winxp5421** [comment]
What version of hashtopussy are you running? What version of the client are you running? can we have "hashtopussy.exe debug" output please? We have no idea what is going on without this information

**Comment by master12210** [comment]
C:\Users\minner1\Desktop\server cracker>hashtopussy.exe debug
Client Version 0.43
Checking for client updates
{"action":"update","type":"csharp","version":"0.43"}
{"action":"update","response":"SUCCESS","version":"OK"}
You are using the latest client version
System is Windows
Existing token found
{"action":"login","token":"M8sRDdLGgA"}
{"action":"login","response":"SUCCESS","timeout":"30"}
Logged in to server
{"action":"download","type":"hashcat","token":"M8sRDdLGgA","force":0}
Hashcat version v3.40 found
Getting task
{"action":"task","token":"M8sRDdLGgA"}
{"action":"task","response":"SUCCESS","task":15,"attackcmd":"-a3 #HL# -1?l?u?d ?1?1?1?1?1?1?1?1","cmdpars":" --hash-type=2500","hashlist":2,"bench":30,"statustimer":5,"files":[],"benchType":"speed","hashlistAlias":"#HL#"}
Downloading hashlist for this task, please wait...
{"action":"hashes","token":"M8sRDdLGgA","hashlist":2}
{"action":"hashes","response":"SUCCESS","data":"SENQWAQAAAAACmJlbGtpbi5mZTkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAh3ZyBC6ODudpdvEqUmRIEvAVifdT+lOR1Wnrp3D+e5C5aDtxR9sTR\/2fn4kZXUdIYeKTpEq4thbKhXRq\/rEUQa9LocvSW5Ia3xYU7N7sxdwt4r4ESadIajVBOaKeQABAwB1AgEKAAAAAAAAAAAAAfrEUQa9LocvSW5Ia3xYU7N7sxdwt4r4ESadIajVBOaKAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABYwFAEAAA+sBAEAAA+sBAEAAA+sAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"}
{"action":"chunk","token":"M8sRDdLGgA","taskId":15}
{"action":"chunk","response":"SUCCESS","status":"keyspace_required"}
Server has requested the client to measure the keyspace for this task
Using C:\Users\minner1\Desktop\server cracker\files\ as working directory
Something went wrong with keyspace measuring
You need to specify a mask if you specify a custom-charset

Unhandled Exception: System.FormatException: Input string was not in a correct format.
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt64(String value, NumberStyles options, NumberFormatInfo numfmt)
   at System.Convert.ToInt64(String value)
   at hashtopussy.hashcatClass.parseKeyspace(String line, Int64& keySpace)
   at hashtopussy.hashcatClass.runKeyspace(Int64& keySpace)
   at hashtopussy.taskClass.getChunk(Int32 inTask)
   at hashtopussy.taskClass.getTask()
   at hashtopussy.Program.Main(String[] args)

C:\Users\minner1\Desktop\server cracker>

Hashtopussy version 0.3.0
Client Version 0.43

**Comment by winxp5421** [comment]
This was a bug found in hashcat-3.40 when using some of the special options we need to use for hashtopussy. Using the beta release of hashcat should remedy this issue https://hashcat.net/beta

**Comment by s3inlc** [comment]
I'll close this now, it's quite clear that this is just the problem which appears on hashcat 3.40 where the keyspace measuring was broken.
